### ISSUE TITLE
scaling tests

### ISSUE THREAD

**Issue by dpaiton** [delvtech/elf-simulations#945]

**Comment by slundqui** [comment]
Test competition pipeline at scale. There are about 60 traders expected, so we stress test the pipeline to see if anvil can handle the volume. The results of this are needed by October 13th to determine if we stick with anvil or we move to a different node

**Comment by slundqui** [comment]
Anvil scaling tests on local laptop

With automine:
Read transactions fail intermittently with arithmetic over/under flow. Added code to bots to retry read calls.
Write transactions fail intermittently with status=0. Can't do retries because the catch is too broad.
Anvil uses lots of memory. Having 100 bots for a total of around ~10000 transactions in automine mode (i.e., one block per transaction) results in 5GB in RAM

With mining through time:
Able to handle about 30 trades per block before getting "out of gas" error (20 trades per block seem stable)
Write transactions fail intermittently with status=0. Anvil reports "Custom contract error"

**Comment by slundqui** [comment]
https://github.com/delvtech/elf-simulations/issues/987 for fixing memory issues.
